<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Swift Mailing List Archive</title>
    <link rel="stylesheet" href="/css/app-13f065ae5e595562a5022c544e3b976c.css?vsn=d">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <img src="/images/swift-d0237fc716ba0932a940049990beba1b.svg?vsn=d" height="70">
      </header>

      <p class="alert alert-info" role="alert"></p>
      <p class="alert alert-danger" role="alert"></p>

    </div> <!-- /container -->
    <main role="main">
<div class="comment-wrapper"><ul class="comments"><li class="comment"><div class="avatar"><img src="https://www.gravatar.com/avatar/3a0ae72b2f6bdc4476f1fcb63396e717?s=50"></div><header><strong>MemoryError in SIL/parse_stdlib_X.sil tests when building toolchain on Ubuntu 15.10</strong> from <string>Jean-Pierre Simard</string> &lt;jp at jpsim.com&gt;<p>August 11, 2016 at 05:00:00pm</p></header><div class="content"><p>Apologies if this is being tracked elsewhere, but I started getting these<br>failures when building the toolchain on Linux.<br></p><p>I triggered this by running utils/update-checkout --clone &amp;&amp;<br>utils/build-toolchain local.swift on a fresh machine. All other tests pass (<br>8457/8459).<br></p><p>Any thoughts as to why this may have started happening? Should I file a<br>ticket a JIRA about this?<br></p><p>On an unrelated note: is there a preset, or extra commands, to skip running<br>the tests when building the toolchain?<br></p><p>Thanks.<br></p><p>===<br></p><p>UNRESOLVED: Swift(linux-x86_64) :: SIL/parse_stdlib_0.sil (8443 of 8459)<br>******************** TEST &#39;Swift(linux-x86_64) :: SIL/parse_stdlib_0.sil&#39;<br>FAILED ********************<br>Exception during script execution:<br>Traceback (most recent call last):<br>  File &quot;/swift-development/llvm/utils/lit/lit/run.py&quot;, line 166, in<br>execute_test<br>    result = test.config.test_format.execute(test, self.lit_config)<br>  File &quot;/swift-development/swift/test/lit.cfg&quot;, line 175, in execute<br>    result = super(SwiftTest, self).execute(test, litConfig)<br>  File &quot;/swift-development/llvm/utils/lit/lit/formats/shtest.py&quot;, line 12,<br>in execute<br>    self.execute_external)<br>  File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 734, in<br>executeShTest<br>    res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)<br>  File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 680, in<br>_runShTest<br>    res = executeScript(test, litConfig, tmpBase, script, execdir)<br>  File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 470, in<br>executeScript<br>    timeout=litConfig.maxIndividualTestTime)<br>  File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 216, in<br>executeCommand<br>    out,err = p.communicate(input=input)<br>  File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 799, in communicate<br>    return self._communicate(input)<br>  File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 1417, in _communicate<br>    stderr = &#39;&#39;.join(stderr)<br>MemoryError<br></p><p><br>********************<br>UNRESOLVED: Swift(linux-x86_64) :: SIL/parse_stdlib_7.sil (8444 of 8459)<br>******************** TEST &#39;Swift(linux-x86_64) :: SIL/parse_stdlib_7.sil&#39;<br>FAILED ********************<br>Exception during script execution:<br>Traceback (most recent call last):<br>  File &quot;/swift-development/llvm/utils/lit/lit/run.py&quot;, line 166, in<br>execute_test<br>    result = test.config.test_format.execute(test, self.lit_config)<br>  File &quot;/swift-development/swift/test/lit.cfg&quot;, line 175, in execute<br>    result = super(SwiftTest, self).execute(test, litConfig)<br>  File &quot;/swift-development/llvm/utils/lit/lit/formats/shtest.py&quot;, line 12,<br>in execute<br>    self.execute_external)<br>  File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 734, in<br>executeShTest<br>    res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)<br>  File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 680, in<br>_runShTest<br>    res = executeScript(test, litConfig, tmpBase, script, execdir)<br>  File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 470, in<br>executeScript<br>    timeout=litConfig.maxIndividualTestTime)<br>  File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 224, in<br>executeCommand<br>    err = convert_string(err)<br>  File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 22, in<br>convert_string<br>    return to_string(bytes.decode(&#39;utf-8&#39;))<br>  File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 18, in<br>to_string<br>    return to_bytes(bytes)<br>  File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 13, in to_bytes<br>    return str.encode(&#39;utf-8&#39;)<br>MemoryError<br>-------------- next part --------------<br>An HTML attachment was scrubbed...<br>URL: &lt;https://lists.swift.org/pipermail/swift-dev/attachments/20160811/cfae2fe4/attachment.html&gt;<br></p></div><ul class="comments"><li class="comment"><div class="avatar"><img src="https://www.gravatar.com/avatar/12dd65fe648ab7baf7b432dd586a8388?s=50"></div><header><strong>MemoryError in SIL/parse_stdlib_X.sil tests when building toolchain on Ubuntu 15.10</strong> from <string>mishal_shah</string> &lt;mishal_shah at apple.com&gt;<p>August 11, 2016 at 10:00:00am</p></header><div class="content"><p>Hi, <br></p><p>Can you please file a bug on bugs.swift.org? Can you please include the commit(sha) you started seeing this? <br></p><p>Thanks, <br>Mishal Shah<br>&gt; On Aug 11, 2016, at 10:10 AM, Jean-Pierre Simard via swift-dev &lt;swift-dev at swift.org&gt; wrote:<br>&gt; <br>&gt; Apologies if this is being tracked elsewhere, but I started getting these failures when building the toolchain on Linux.<br>&gt; <br>&gt; I triggered this by running utils/update-checkout --clone &amp;&amp; utils/build-toolchain local.swift on a fresh machine. All other tests pass (8457/8459).<br>&gt; <br>&gt; Any thoughts as to why this may have started happening? Should I file a ticket a JIRA about this?<br>&gt; <br>&gt; On an unrelated note: is there a preset, or extra commands, to skip running the tests when building the toolchain?<br>&gt; <br>&gt; Thanks.<br>&gt; <br>&gt; ===<br>&gt; <br>&gt; UNRESOLVED: Swift(linux-x86_64) :: SIL/parse_stdlib_0.sil (8443 of 8459)<br>&gt; ******************** TEST &#39;Swift(linux-x86_64) :: SIL/parse_stdlib_0.sil&#39; FAILED ********************<br>&gt; Exception during script execution:<br>&gt; Traceback (most recent call last):<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/run.py&quot;, line 166, in execute_test<br>&gt;     result = test.config.test_format.execute(test, self.lit_config)<br>&gt;   File &quot;/swift-development/swift/test/lit.cfg&quot;, line 175, in execute<br>&gt;     result = super(SwiftTest, self).execute(test, litConfig)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/formats/shtest.py&quot;, line 12, in execute<br>&gt;     self.execute_external)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 734, in executeShTest<br>&gt;     res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 680, in _runShTest<br>&gt;     res = executeScript(test, litConfig, tmpBase, script, execdir)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 470, in executeScript<br>&gt;     timeout=litConfig.maxIndividualTestTime)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 216, in executeCommand<br>&gt;     out,err = p.communicate(input=input)<br>&gt;   File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 799, in communicate<br>&gt;     return self._communicate(input)<br>&gt;   File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 1417, in _communicate<br>&gt;     stderr = &#39;&#39;.join(stderr)<br>&gt; MemoryError<br>&gt; <br>&gt; <br>&gt; ********************<br>&gt; UNRESOLVED: Swift(linux-x86_64) :: SIL/parse_stdlib_7.sil (8444 of 8459)<br>&gt; ******************** TEST &#39;Swift(linux-x86_64) :: SIL/parse_stdlib_7.sil&#39; FAILED ********************<br>&gt; Exception during script execution:<br>&gt; Traceback (most recent call last):<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/run.py&quot;, line 166, in execute_test<br>&gt;     result = test.config.test_format.execute(test, self.lit_config)<br>&gt;   File &quot;/swift-development/swift/test/lit.cfg&quot;, line 175, in execute<br>&gt;     result = super(SwiftTest, self).execute(test, litConfig)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/formats/shtest.py&quot;, line 12, in execute<br>&gt;     self.execute_external)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 734, in executeShTest<br>&gt;     res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 680, in _runShTest<br>&gt;     res = executeScript(test, litConfig, tmpBase, script, execdir)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 470, in executeScript<br>&gt;     timeout=litConfig.maxIndividualTestTime)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 224, in executeCommand<br>&gt;     err = convert_string(err)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 22, in convert_string<br>&gt;     return to_string(bytes.decode(&#39;utf-8&#39;))<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 18, in to_string<br>&gt;     return to_bytes(bytes)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 13, in to_bytes<br>&gt;     return str.encode(&#39;utf-8&#39;)<br>&gt; MemoryError<br>&gt; <br>&gt; _______________________________________________<br>&gt; swift-dev mailing list<br>&gt; swift-dev at swift.org<br>&gt; https://lists.swift.org/mailman/listinfo/swift-dev<br></p><p>-------------- next part --------------<br>An HTML attachment was scrubbed...<br>URL: &lt;https://lists.swift.org/pipermail/swift-dev/attachments/20160811/8c78c481/attachment.html&gt;<br></p></div><ul class="comments"><li class="comment"><div class="avatar"><img src="https://www.gravatar.com/avatar/c4fe988326eed161b989d0c5521cb105?s=50"></div><header><strong>MemoryError in SIL/parse_stdlib_X.sil tests when building toolchain on Ubuntu 15.10</strong> from <string>Jordan Rose</string> &lt;jordan_rose at apple.com&gt;<p>August 11, 2016 at 10:00:00am</p></header><div class="content"><p>I think this is the spew of deprecation warnings thing I was investigating yesterday. I just merged the fix for that, so try updating to the latest master and try again.<br></p><p>Jordan<br></p><p><br>&gt; On Aug 11, 2016, at 10:21, Mishal Shah via swift-dev &lt;swift-dev at swift.org&gt; wrote:<br>&gt; <br>&gt; Hi, <br>&gt; <br>&gt; Can you please file a bug on bugs.swift.org &lt;http://bugs.swift.org/&gt;? Can you please include the commit(sha) you started seeing this? <br>&gt; <br>&gt; Thanks, <br>&gt; Mishal Shah<br>&gt;&gt; On Aug 11, 2016, at 10:10 AM, Jean-Pierre Simard via swift-dev &lt;swift-dev at swift.org &lt;mailto:swift-dev at swift.org&gt;&gt; wrote:<br>&gt;&gt; <br>&gt;&gt; Apologies if this is being tracked elsewhere, but I started getting these failures when building the toolchain on Linux.<br>&gt;&gt; <br>&gt;&gt; I triggered this by running utils/update-checkout --clone &amp;&amp; utils/build-toolchain local.swift on a fresh machine. All other tests pass (8457/8459).<br>&gt;&gt; <br>&gt;&gt; Any thoughts as to why this may have started happening? Should I file a ticket a JIRA about this?<br>&gt;&gt; <br>&gt;&gt; On an unrelated note: is there a preset, or extra commands, to skip running the tests when building the toolchain?<br>&gt;&gt; <br>&gt;&gt; Thanks.<br>&gt;&gt; <br>&gt;&gt; ===<br>&gt;&gt; <br>&gt;&gt; UNRESOLVED: Swift(linux-x86_64) :: SIL/parse_stdlib_0.sil (8443 of 8459)<br>&gt;&gt; ******************** TEST &#39;Swift(linux-x86_64) :: SIL/parse_stdlib_0.sil&#39; FAILED ********************<br>&gt;&gt; Exception during script execution:<br>&gt;&gt; Traceback (most recent call last):<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/run.py&quot;, line 166, in execute_test<br>&gt;&gt;     result = test.config.test_format.execute(test, self.lit_config)<br>&gt;&gt;   File &quot;/swift-development/swift/test/lit.cfg&quot;, line 175, in execute<br>&gt;&gt;     result = super(SwiftTest, self).execute(test, litConfig)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/formats/shtest.py&quot;, line 12, in execute<br>&gt;&gt;     self.execute_external)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 734, in executeShTest<br>&gt;&gt;     res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 680, in _runShTest<br>&gt;&gt;     res = executeScript(test, litConfig, tmpBase, script, execdir)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 470, in executeScript<br>&gt;&gt;     timeout=litConfig.maxIndividualTestTime)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 216, in executeCommand<br>&gt;&gt;     out,err = p.communicate(input=input)<br>&gt;&gt;   File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 799, in communicate<br>&gt;&gt;     return self._communicate(input)<br>&gt;&gt;   File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 1417, in _communicate<br>&gt;&gt;     stderr = &#39;&#39;.join(stderr)<br>&gt;&gt; MemoryError<br>&gt;&gt; <br>&gt;&gt; <br>&gt;&gt; ********************<br>&gt;&gt; UNRESOLVED: Swift(linux-x86_64) :: SIL/parse_stdlib_7.sil (8444 of 8459)<br>&gt;&gt; ******************** TEST &#39;Swift(linux-x86_64) :: SIL/parse_stdlib_7.sil&#39; FAILED ********************<br>&gt;&gt; Exception during script execution:<br>&gt;&gt; Traceback (most recent call last):<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/run.py&quot;, line 166, in execute_test<br>&gt;&gt;     result = test.config.test_format.execute(test, self.lit_config)<br>&gt;&gt;   File &quot;/swift-development/swift/test/lit.cfg&quot;, line 175, in execute<br>&gt;&gt;     result = super(SwiftTest, self).execute(test, litConfig)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/formats/shtest.py&quot;, line 12, in execute<br>&gt;&gt;     self.execute_external)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 734, in executeShTest<br>&gt;&gt;     res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 680, in _runShTest<br>&gt;&gt;     res = executeScript(test, litConfig, tmpBase, script, execdir)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 470, in executeScript<br>&gt;&gt;     timeout=litConfig.maxIndividualTestTime)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 224, in executeCommand<br>&gt;&gt;     err = convert_string(err)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 22, in convert_string<br>&gt;&gt;     return to_string(bytes.decode(&#39;utf-8&#39;))<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 18, in to_string<br>&gt;&gt;     return to_bytes(bytes)<br>&gt;&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 13, in to_bytes<br>&gt;&gt;     return str.encode(&#39;utf-8&#39;)<br>&gt;&gt; MemoryError<br>&gt;&gt; <br>&gt;&gt; _______________________________________________<br>&gt;&gt; swift-dev mailing list<br>&gt;&gt; swift-dev at swift.org &lt;mailto:swift-dev at swift.org&gt;<br>&gt;&gt; https://lists.swift.org/mailman/listinfo/swift-dev<br>&gt; <br>&gt; _______________________________________________<br>&gt; swift-dev mailing list<br>&gt; swift-dev at swift.org<br>&gt; https://lists.swift.org/mailman/listinfo/swift-dev<br></p><p>-------------- next part --------------<br>An HTML attachment was scrubbed...<br>URL: &lt;https://lists.swift.org/pipermail/swift-dev/attachments/20160811/652b33f1/attachment.html&gt;<br></p></div><ul class="comments"><li class="comment"><div class="avatar"><img src="https://www.gravatar.com/avatar/3a0ae72b2f6bdc4476f1fcb63396e717?s=50"></div><header><strong>MemoryError in SIL/parse_stdlib_X.sil tests when building toolchain on Ubuntu 15.10</strong> from <string>Jean-Pierre Simard</string> &lt;jp at jpsim.com&gt;<p>August 11, 2016 at 06:00:00pm</p></header><div class="content"><p>Thanks Jordan, that fixed it! Sorry for the noise here, will go straight to<br>file a bug next time.<br></p><p>On Thu, 11 Aug 2016 at 10:26 Jordan Rose &lt;jordan_rose at apple.com&gt; wrote:<br></p><p>&gt; I think this is the spew of deprecation warnings thing I was investigating<br>&gt; yesterday. I just merged the fix for that, so try updating to the latest<br>&gt; master and try again.<br>&gt;<br>&gt; Jordan<br>&gt;<br>&gt;<br>&gt; On Aug 11, 2016, at 10:21, Mishal Shah via swift-dev &lt;swift-dev at swift.org&gt;<br>&gt; wrote:<br>&gt;<br>&gt; Hi,<br>&gt;<br>&gt; Can you please file a bug on bugs.swift.org? Can you please include the<br>&gt; commit(sha) you started seeing this?<br>&gt;<br>&gt; Thanks,<br>&gt; Mishal Shah<br>&gt;<br>&gt; On Aug 11, 2016, at 10:10 AM, Jean-Pierre Simard via swift-dev &lt;<br>&gt; swift-dev at swift.org&gt; wrote:<br>&gt;<br>&gt; Apologies if this is being tracked elsewhere, but I started getting these<br>&gt; failures when building the toolchain on Linux.<br>&gt;<br>&gt; I triggered this by running utils/update-checkout --clone &amp;&amp;<br>&gt; utils/build-toolchain local.swift on a fresh machine. All other tests<br>&gt; pass (8457/8459).<br>&gt;<br>&gt; Any thoughts as to why this may have started happening? Should I file a<br>&gt; ticket a JIRA about this?<br>&gt;<br>&gt; On an unrelated note: is there a preset, or extra commands, to skip<br>&gt; running the tests when building the toolchain?<br>&gt;<br>&gt; Thanks.<br>&gt;<br>&gt; ===<br>&gt;<br>&gt; UNRESOLVED: Swift(linux-x86_64) :: SIL/parse_stdlib_0.sil (8443 of 8459)<br>&gt; ******************** TEST &#39;Swift(linux-x86_64) :: SIL/parse_stdlib_0.sil&#39;<br>&gt; FAILED ********************<br>&gt; Exception during script execution:<br>&gt; Traceback (most recent call last):<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/run.py&quot;, line 166, in<br>&gt; execute_test<br>&gt;     result = test.config.test_format.execute(test, self.lit_config)<br>&gt;   File &quot;/swift-development/swift/test/lit.cfg&quot;, line 175, in execute<br>&gt;     result = super(SwiftTest, self).execute(test, litConfig)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/formats/shtest.py&quot;, line 12,<br>&gt; in execute<br>&gt;     self.execute_external)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 734, in<br>&gt; executeShTest<br>&gt;     res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 680, in<br>&gt; _runShTest<br>&gt;     res = executeScript(test, litConfig, tmpBase, script, execdir)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 470, in<br>&gt; executeScript<br>&gt;     timeout=litConfig.maxIndividualTestTime)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 216, in<br>&gt; executeCommand<br>&gt;     out,err = p.communicate(input=input)<br>&gt;   File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 799, in communicate<br>&gt;     return self._communicate(input)<br>&gt;   File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 1417, in _communicate<br>&gt;     stderr = &#39;&#39;.join(stderr)<br>&gt; MemoryError<br>&gt;<br>&gt;<br>&gt; ********************<br>&gt; UNRESOLVED: Swift(linux-x86_64) :: SIL/parse_stdlib_7.sil (8444 of 8459)<br>&gt; ******************** TEST &#39;Swift(linux-x86_64) :: SIL/parse_stdlib_7.sil&#39;<br>&gt; FAILED ********************<br>&gt; Exception during script execution:<br>&gt; Traceback (most recent call last):<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/run.py&quot;, line 166, in<br>&gt; execute_test<br>&gt;     result = test.config.test_format.execute(test, self.lit_config)<br>&gt;   File &quot;/swift-development/swift/test/lit.cfg&quot;, line 175, in execute<br>&gt;     result = super(SwiftTest, self).execute(test, litConfig)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/formats/shtest.py&quot;, line 12,<br>&gt; in execute<br>&gt;     self.execute_external)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 734, in<br>&gt; executeShTest<br>&gt;     res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 680, in<br>&gt; _runShTest<br>&gt;     res = executeScript(test, litConfig, tmpBase, script, execdir)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/TestRunner.py&quot;, line 470, in<br>&gt; executeScript<br>&gt;     timeout=litConfig.maxIndividualTestTime)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 224, in<br>&gt; executeCommand<br>&gt;     err = convert_string(err)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 22, in<br>&gt; convert_string<br>&gt;     return to_string(bytes.decode(&#39;utf-8&#39;))<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 18, in<br>&gt; to_string<br>&gt;     return to_bytes(bytes)<br>&gt;   File &quot;/swift-development/llvm/utils/lit/lit/util.py&quot;, line 13, in<br>&gt; to_bytes<br>&gt;     return str.encode(&#39;utf-8&#39;)<br>&gt; MemoryError<br>&gt;<br>&gt; _______________________________________________<br>&gt; swift-dev mailing list<br>&gt; swift-dev at swift.org<br>&gt; https://lists.swift.org/mailman/listinfo/swift-dev<br>&gt;<br>&gt;<br>&gt; _______________________________________________<br>&gt; swift-dev mailing list<br>&gt; swift-dev at swift.org<br>&gt; https://lists.swift.org/mailman/listinfo/swift-dev<br>&gt;<br>&gt;<br>&gt;<br>-------------- next part --------------<br>An HTML attachment was scrubbed...<br>URL: &lt;https://lists.swift.org/pipermail/swift-dev/attachments/20160811/77adf640/attachment.html&gt;<br></p></div></li></ul></li></ul></li></ul></li></ul></div>    </main>
    <script src="/js/app-c283ee129de63ad743722e9511e67a5d.js?vsn=d"></script>
  </body>
  <footer>
    <p>Swift and the Swift logo are trademarks of Apple Inc.</p>
  </footer>
</html>
